### ISSUE TITLE
Upload current always uploads to main.py, even if current buffer has another name

### ISSUE THREAD

**Issue by oden72** [jim-at-jibba/micropython.nvim#4]
Hi,
Thank you for this plugin. I just discovered it and it will surely be very useful. 

I have been flumoxxed by my updates to a file originally uploaded directly with ampy has not been updated even if MPUpload reported success. After some searching I have concluded the following. 

It seems to me there is a bug in M.pm_upload_current() in file run.lua. The temporary file to be uploaded is always /tmp/main.py and will be named main.py on the microcontroller. If the current file is something else, e.g. a MicroPython library file, it will be uploaded as main.py. The name main.py is passed to assemble_command in the same file. 

Cheers,

**Comment by jim-at-jibba** [comment]
Hey, buddy

Sorry I completely missed this issue. I think this was by design but can see how it could also be seen as a bug. I think when I wrote this I was just writing one script toy projects.

Not sure when I will get a chance to look at this but I will happily review a PR if you want to submit one. Obviously fine if not. 

Thanks for pointing this out to me

**Comment by oden72** [comment]
PR submitted. It was in the works when you answered :-).

**Comment by jim-at-jibba** [comment]
@oden72 Thanks for the PR
